### ISSUE TITLE
Missing Intrinsics

### ISSUE THREAD

**Issue by junyang224** [ihtishamaliktk/RWHE-Calib#1]
Hello, I cannot find the intrinsics in the provided dataset, is it missing? Where I can find it?

Thanks
Jun

**Comment by ihtishamaliktk** [comment]
Hi Jun, 
 The camera intrinsics are estimated in the main file. The function `CalibrateIntrinsics()` returns `cameraParams`(camera parameters object) which includes the camera intrinsic. You can save them from there if you wish to use the dataset seperately.

**Comment by junyang224** [comment]
Hello:

Do we need to estimate the intrinsics even for the simulated data? Or it can be provided from your simulator (the estimated may not be super accurate since you added noise on the simulated data)

Thanks
Jun

**Comment by ihtishamaliktk** [comment]
Unfortunately, I no longer have the original simulator, data loss :(. However, for most cases, the estimated intrinsics should be good enough since the images are synthetic with no noise added.  

In the code provided, we do not induce noise in the default situation (you can check in the `H2EConfiguration.m` file that all noise parameters are set to empty).   So you can directly use the camera parameters that are estimated from the algorithm.

**Comment by junyang224** [comment]
sounds great, thanks!
